# Generated by Django 4.2.3 on 2023-07-14 18:58

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gurukul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('seo', jsonfield.fields.JSONField()),
                ('meta', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category', models.CharField(choices=[('cat1', 'Category 1'), ('cat2', 'Category 2'), ('cat3', 'Category 3')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('course_description', models.TextField()),
                ('course_author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', jsonfield.fields.JSONField(null=True)),
                ('seo', jsonfield.fields.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=10)),
            ],
        ),
    ]
