# Generated by Django 4.2.3 on 2023-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurukul', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=True, max_length=8),
        ),
    ]
